package farmacia;

import javax.swing.*;

public class Formulario extends javax.swing.JFrame {

    public Formulario() {
        initComponents();
        nameField.setDocument(new textLimiter(20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distributorGroup = new javax.swing.ButtonGroup();
        nameLabel = new javax.swing.JLabel();
        medicineTypeLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        distribuitorLabel = new javax.swing.JLabel();
        sucoursalLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        medicineTypebox = new javax.swing.JComboBox<>();
        quantityField = new javax.swing.JTextField();
        cofarmaButton = new javax.swing.JRadioButton();
        empsepharButton = new javax.swing.JRadioButton();
        cemefarButton = new javax.swing.JRadioButton();
        mainBox = new javax.swing.JCheckBox();
        secondaryBox = new javax.swing.JCheckBox();
        deleteButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        nameError = new javax.swing.JLabel();
        distributorError = new javax.swing.JLabel();
        sucoursalError = new javax.swing.JLabel();
        quantityError = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Nombre del Medicamento");

        medicineTypeLabel.setText("Tipo del Medicamento");

        quantityLabel.setText("Cantidad del Producto");

        distribuitorLabel.setText("Distribuidor");

        sucoursalLabel.setText("Sucursal");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        medicineTypebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibiótico" }));
        medicineTypebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineTypeboxActionPerformed(evt);
            }
        });

        distributorGroup.add(cofarmaButton);
        cofarmaButton.setText("Cofarma");
        cofarmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofarmaButtonActionPerformed(evt);
            }
        });

        distributorGroup.add(empsepharButton);
        empsepharButton.setText("Empsephar");

        distributorGroup.add(cemefarButton);
        cemefarButton.setText("Cemefar");

        mainBox.setText("Principal");
        mainBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBoxActionPerformed(evt);
            }
        });

        secondaryBox.setText("Secundaria");

        deleteButton.setText("BORRAR");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("CONFIRMAR");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        nameError.setForeground(new java.awt.Color(255, 0, 0));

        distributorError.setForeground(new java.awt.Color(255, 0, 0));

        sucoursalError.setForeground(new java.awt.Color(255, 0, 0));

        quantityError.setBackground(new java.awt.Color(255, 0, 0));
        quantityError.setForeground(new java.awt.Color(255, 0, 0));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("FORMULARIO PARA PEDIDOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medicineTypeLabel)
                                    .addComponent(quantityLabel))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityField)
                                    .addComponent(medicineTypebox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameError, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(quantityError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(distributorError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(distribuitorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cofarmaButton)
                                        .addComponent(empsepharButton)
                                        .addComponent(cemefarButton))))
                            .addComponent(deleteButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(confirmButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sucoursalError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sucoursalLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(secondaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mainBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 80, Short.MAX_VALUE)))))))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicineTypeLabel)
                    .addComponent(medicineTypebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityLabel)
                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quantityError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cofarmaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empsepharButton)
                            .addComponent(distribuitorLabel)
                            .addComponent(sucoursalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cemefarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondaryBox)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distributorError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sucoursalError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(confirmButton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicineTypeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineTypeboxActionPerformed

    }//GEN-LAST:event_medicineTypeboxActionPerformed

    private void cofarmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofarmaButtonActionPerformed

    }//GEN-LAST:event_cofarmaButtonActionPerformed

    private void mainBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBoxActionPerformed

    }//GEN-LAST:event_mainBoxActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        boolean ready = true;

        if (quantityField.getText().length() == 0) {
            quantityError.setText("Cantidad no introducida");
            ready = false;
        } else if (!quantityField.getText().matches("^[0-9\s]+$")) {
            quantityError.setText("La cantidad debe ser numérica");
            ready = false;
        } else {
            quantityError.setText("");
            //ready = true;
        }

        if (nameField.getText().length() == 0) {
            nameError.setText("Es necesario introducir un nombre de medicamento");
            ready = false;

        } else if (!nameField.getText().matches("^[A-ZAa-zA0-9A \s]+$")) {
            nameError.setText("Solo se aceptan letras de A - Z y números del 0 - 9");
            ready = false;

        } else {
            nameError.setText("");
            //ready = true;
        }

        if (!cofarmaButton.isSelected() && !empsepharButton.isSelected() && !cemefarButton.isSelected()) {
            distributorError.setText("Debe seleccionar un distribuidor");
            ready = false;
        } else {
            distributorError.setText("");
            //ready = true;
        }

        int estado = 0;

        if (mainBox.isSelected()) {
            estado++;
        }
        if (secondaryBox.isSelected()) {
            estado = estado + 2;
        }
        if (estado == 0) {
            sucoursalError.setText("Debe seleccionar una sucursal");
            //ready = false;
        } else {
            sucoursalError.setText("");
        }

        if (ready) {
            Confirmacion conf = new Confirmacion();
            conf.setVisible(true);
            conf.setdistributorOrderLabel(getDistributor());
            conf.setorderInfoLabel(getQuantity(), getMedicineType(), getName());
            conf.setlocationOrderLabel(estado);
            System.out.println("Pedido enviado");
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        nameField.setText("");
        quantityField.setText("");
        distributorGroup.clearSelection();
        mainBox.setSelected(false);
        secondaryBox.setSelected(false);
        quantityError.setText("");
        nameError.setText("");
        distributorError.setText("");
        sucoursalError.setText("");
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed


    }//GEN-LAST:event_nameFieldActionPerformed

    @Override
    public String getName() {
        return nameField.getText();
    }

    public String getMedicineType() {
        return medicineTypebox.getSelectedItem().toString();
    }

    public String getQuantity() {
        return quantityField.getText();
    }

    public String getDistributor() {
        String distributor = "";
        if (cofarmaButton.isSelected()) {
            distributor = "Cofarma";
        }
        if (empsepharButton.isSelected()) {
            distributor = "Empsephar";
        }
        if (cemefarButton.isSelected()) {
            distributor = "Cemefar";
        }
        return distributor;
    }

    public String getSucoursal() {
        String sucoursal = "";
        if (mainBox.isSelected()) {
            sucoursal = "Principal";
        }
        if (secondaryBox.isSelected()) {
            sucoursal = "Secundaria";
        }
        return sucoursal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cemefarButton;
    private javax.swing.JRadioButton cofarmaButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel distribuitorLabel;
    private javax.swing.JLabel distributorError;
    private javax.swing.ButtonGroup distributorGroup;
    private javax.swing.JRadioButton empsepharButton;
    private javax.swing.JCheckBox mainBox;
    private javax.swing.JLabel medicineTypeLabel;
    private javax.swing.JComboBox<String> medicineTypebox;
    private javax.swing.JLabel nameError;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel quantityError;
    private javax.swing.JTextField quantityField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JCheckBox secondaryBox;
    private javax.swing.JLabel sucoursalError;
    private javax.swing.JLabel sucoursalLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
